name: Release & Publish

on:
  release:
    types:
      - published

permissions:
  id-token: write   # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check github.ref starts with 'refs/tags/'
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo Error! github.ref does not start with 'refs/tags'
          echo github.ref: ${{ github.ref }}
          exit 1
      - name: Set version number environment variable
        env:
          github_ref: ${{ github.ref }}
        run: |
          ref="${github_ref:10}"
          echo $ref
          echo "ref=$ref" >> $GITHUB_ENV
          # Detect if this is a prerelease version (contains -, like 1.0.0-beta.1)
          if [[ "$ref" == *"-"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_ENV
            # Extract the prerelease tag (e.g., "beta" from "1.0.0-beta.1")
            prerelease_tag=$(echo "$ref" | sed -E 's/[0-9]+\.[0-9]+\.[0-9]+-([a-zA-Z]+).*/\1/')
            echo "prerelease_tag=$prerelease_tag" >> $GITHUB_ENV
          else
            echo "is_prerelease=false" >> $GITHUB_ENV
          fi
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: npm ci
      - name: Build
        run: npm run build
      - name: Configure package name, url, and version
        env:
          github_repo: ${{ github.repository }}
        run: node tools/updateurl $github_repo $ref
      - name: Clean package.json
        run: node tools/prepare-publish
      - name: Publish to npm
        run: |
          if [ "${{ env.is_prerelease }}" = "true" ]; then
            npm publish --provenance --access public --tag ${{ env.prerelease_tag }}
          else
            npm publish --provenance --access public
          fi
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Configure package name, url, and version
        env:
          github_repo: ${{ github.repository }}
        run: node tools/updateurl $github_repo $ref
      - name: Clean package.json
        run: node tools/prepare-publish
      - name: Publish to GitHub Packages
        run: |
          if [ "${{ env.is_prerelease }}" = "true" ]; then
            npm publish --tag ${{ env.prerelease_tag }}
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
