name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
#          - windows-latest
        node: 
          - 18.x
          - 19.x
        react:
          - 16
          - 17
          - 18
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Update npm
        run: npm install -g npm@9
      - name: Install modules - actor ${{ github.actor }} - version ${{ github.run_number }}
        run: npm ci
      - name: Install react
        run: npm install react@^${{ matrix.react }} react-dom@^${{ matrix.react }} @types/react@^${{ matrix.react }} @types/react-dom@^${{ matrix.react }} @testing-library/react@^${{ matrix.react == '18' && '13' || '12' }} --save-dev
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test
