name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
#          - windows-latest
        node: 
          - 18.x
          - 20.x
          - 22.x
          - 23.x
          - 24.x
        react:
          - 16
          - 17
          - 18
          - 19
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules - actor ${{ github.actor }} - version ${{ github.run_number }}
        run: npm ci
      - name: Install react
        run: npm install react@^${{ matrix.react }} react-dom@^${{ matrix.react }} @types/react@^${{ matrix.react }} @types/react-dom@^${{ matrix.react }} @testing-library/react@^${{ (matrix.react == '19' || matrix.react == '18') && '16' || '12' }} ${{ (matrix.react == '19' || matrix.react == '18') && '@testing-library/dom@10' || ''  }} --save-dev
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install modules
        run: npm ci
      - name: Format check
        run: npm run test-prettier
