name: Test

on:
  pull_request:

jobs:
  test-react16:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
#          - windows-latest
        node: 
          - 14.x
          - 16.x
#          - 18.x

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules - actor ${{ github.actor }} - version ${{ github.run_number }}
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test
  test-react18:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
#          - windows-latest
        node: 
          - 14.x
          - 16.x
#          - 18.x

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules - actor ${{ github.actor }} - version ${{ github.run_number }}
        run: npm ci
      - name: Install react
        run: npm install react@^18 react-dom@^18 @types/react@^18 @types/react-dom@^18 @testing-library/react@^13 --save-dev
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test
